# -*- coding: utf-8 -*-
# Data for pan-India "Best Astrologer in <State/City>" pages.
# fact = one short, safe, widely-known descriptive line used to make each
# page's intro paragraph distinct (not a claim about the astrology business).

STATES = [
    dict(name="Andhra Pradesh", slug="andhra-pradesh", capital="Amaravati", region="South India",
         fact="home to Tirupati, one of the world's most visited pilgrimage sites, and a fast-growing IT and pharma hub",
         lat=16.5062, lon=80.6480),
    dict(name="Arunachal Pradesh", slug="arunachal-pradesh", capital="Itanagar", region="Northeast India",
         fact="India's easternmost state, known for its Himalayan monasteries and tribal heritage",
         lat=27.0844, lon=93.6053),
    dict(name="Assam", slug="assam", capital="Dispur (Guwahati)", region="Northeast India",
         fact="the gateway to Northeast India, known for tea gardens, the Brahmaputra river and Kamakhya Temple",
         lat=26.1445, lon=91.7362),
    dict(name="Bihar", slug="bihar", capital="Patna", region="East India",
         fact="one of India's most historic states, home to Bodh Gaya and the ancient seat of learning at Nalanda",
         lat=25.5941, lon=85.1376),
    dict(name="Chhattisgarh", slug="chhattisgarh", capital="Raipur", region="Central India",
         fact="a mineral-rich central Indian state known for its forests, waterfalls and tribal culture",
         lat=21.2514, lon=81.6296),
    dict(name="Goa", slug="goa", capital="Panaji", region="West India",
         fact="India's smallest state by area, famed for its beaches and Indo-Portuguese heritage",
         lat=15.4909, lon=73.8278),
    dict(name="Gujarat", slug="gujarat", capital="Gandhinagar", region="West India",
         fact="a major industrial and business hub, home to Ahmedabad, Surat and the Rann of Kutch",
         lat=23.2156, lon=72.6369),
    dict(name="Haryana", slug="haryana", capital="Chandigarh", region="North India",
         fact="an agricultural and industrial state bordering Delhi, home to Gurugram's corporate hub",
         lat=30.7333, lon=76.7794),
    dict(name="Himachal Pradesh", slug="himachal-pradesh", capital="Shimla", region="North India",
         fact="a Himalayan state known for its hill stations, apple orchards and temples",
         lat=31.1048, lon=77.1734),
    dict(name="Jharkhand", slug="jharkhand", capital="Ranchi", region="East India",
         fact="a mineral-rich plateau state known for its waterfalls and industrial towns",
         lat=23.3441, lon=85.3096),
    dict(name="Karnataka", slug="karnataka", capital="Bengaluru", region="South India",
         fact="home to Bengaluru, India's technology capital, along with Mysuru's royal heritage",
         lat=12.9716, lon=77.5946),
    dict(name="Kerala", slug="kerala", capital="Thiruvananthapuram", region="South India",
         fact="known as God's Own Country for its backwaters, hill stations and high literacy",
         lat=8.5241, lon=76.9366),
    dict(name="Madhya Pradesh", slug="madhya-pradesh", capital="Bhopal", region="Central India",
         fact="the geographic heart of India, home to Khajuraho and several tiger reserves",
         lat=23.2599, lon=77.4126),
    dict(name="Maharashtra", slug="maharashtra", capital="Mumbai", region="West India",
         fact="home to Mumbai, India's financial capital and the entertainment hub of Bollywood",
         lat=19.0760, lon=72.8777),
    dict(name="Manipur", slug="manipur", capital="Imphal", region="Northeast India",
         fact="a scenic Northeast state known for Loktak Lake and its rich classical dance heritage",
         lat=24.8170, lon=93.9368),
    dict(name="Meghalaya", slug="meghalaya", capital="Shillong", region="Northeast India",
         fact="known as the abode of clouds, home to some of the wettest places on Earth",
         lat=25.5788, lon=91.8933),
    dict(name="Mizoram", slug="mizoram", capital="Aizawl", region="Northeast India",
         fact="a hilly Northeast state known for its forests and high literacy rate",
         lat=23.1645, lon=92.9376),
    dict(name="Nagaland", slug="nagaland", capital="Kohima", region="Northeast India",
         fact="known for its tribal culture and the annual Hornbill Festival",
         lat=25.6751, lon=94.1086),
    dict(name="Odisha", slug="odisha", capital="Bhubaneswar", region="East India",
         fact="home to the Jagannath Temple in Puri and the Sun Temple at Konark",
         lat=20.2961, lon=85.8245),
    dict(name="Punjab", slug="punjab", capital="Chandigarh", region="North India",
         fact="India's agricultural heartland, home to the Golden Temple in Amritsar",
         lat=30.7333, lon=76.7794),
    dict(name="Rajasthan", slug="rajasthan", capital="Jaipur", region="North India",
         fact="the land of forts and palaces, home to Jaipur, Udaipur and the Thar Desert",
         lat=26.9124, lon=75.7873),
    dict(name="Sikkim", slug="sikkim", capital="Gangtok", region="Northeast India",
         fact="a Himalayan state at the foot of Kangchenjunga, India's first fully organic state",
         lat=27.3389, lon=88.6065),
    dict(name="Tamil Nadu", slug="tamil-nadu", capital="Chennai", region="South India",
         fact="home to ancient Dravidian temples and Chennai, a major automobile and IT hub",
         lat=13.0827, lon=80.2707),
    dict(name="Telangana", slug="telangana", capital="Hyderabad", region="South India",
         fact="home to Hyderabad, a major IT and pharma hub known for its Nizami heritage",
         lat=17.3850, lon=78.4867),
    dict(name="Tripura", slug="tripura", capital="Agartala", region="Northeast India",
         fact="a Northeast state known for the Ujjayanta Palace and Tripura Sundari Temple",
         lat=23.8315, lon=91.2868),
    dict(name="Uttar Pradesh", slug="uttar-pradesh", capital="Lucknow", region="North India",
         fact="India's most populous state, home to the Taj Mahal in Agra and Varanasi's ghats",
         lat=26.8467, lon=80.9462),
    dict(name="Uttarakhand", slug="uttarakhand", capital="Dehradun", region="North India",
         fact="the land of the Char Dham pilgrimage, nestled in the Himalayan foothills",
         lat=30.3165, lon=78.0322),
    dict(name="West Bengal", slug="west-bengal", capital="Kolkata", region="East India",
         fact="home to Kolkata, India's cultural capital, and the Sundarbans mangrove delta",
         lat=22.5726, lon=88.3639),
    # Union Territories
    dict(name="Andaman and Nicobar Islands", slug="andaman-and-nicobar-islands", capital="Port Blair", region="Island Territory",
         fact="a tropical island territory in the Bay of Bengal known for its beaches and coral reefs",
         lat=11.6234, lon=92.7265),
    dict(name="Chandigarh", slug="chandigarh", capital="Chandigarh", region="North India",
         fact="a planned city that serves as the joint capital of Punjab and Haryana",
         lat=30.7333, lon=76.7794),
    dict(name="Dadra and Nagar Haveli and Daman and Diu", slug="dadra-and-nagar-haveli-and-daman-and-diu", capital="Daman", region="West India",
         fact="a coastal union territory on India's west coast with strong Portuguese-era heritage",
         lat=20.3974, lon=72.8328),
    dict(name="Delhi", slug="delhi", capital="New Delhi", region="North India",
         fact="India's national capital and a major hub for business, government and culture",
         lat=28.7041, lon=77.1025),
    dict(name="Jammu and Kashmir", slug="jammu-and-kashmir", capital="Srinagar", region="North India",
         fact="known as paradise on earth for its valleys, lakes and Himalayan scenery",
         lat=34.0837, lon=74.7973),
    dict(name="Ladakh", slug="ladakh", capital="Leh", region="North India",
         fact="a high-altitude Himalayan region known for its monasteries and dramatic landscapes",
         lat=34.1526, lon=77.5771),
    dict(name="Lakshadweep", slug="lakshadweep", capital="Kavaratti", region="Island Territory",
         fact="India's smallest union territory, a cluster of coral islands in the Arabian Sea",
         lat=10.5667, lon=72.6417),
    dict(name="Puducherry", slug="puducherry", capital="Puducherry", region="South India",
         fact="a former French colony on the southeast coast known for its coastal promenade",
         lat=11.9416, lon=79.8083),
]

# name, state (full name), lat, lon, one-line fact
CITIES = [
    ("Mumbai", "Maharashtra", 19.0760, 72.8777, "India's financial capital and home to Bollywood"),
    ("Delhi", "Delhi", 28.7041, 77.1025, "India's national capital and seat of government"),
    ("Bengaluru", "Karnataka", 12.9716, 77.5946, "India's technology and startup capital"),
    ("Hyderabad", "Telangana", 17.3850, 78.4867, "a major IT and pharma hub known for its Nizami heritage"),
    ("Ahmedabad", "Gujarat", 23.0225, 72.5714, "Gujarat's largest city and a major textile and business centre"),
    ("Chennai", "Tamil Nadu", 13.0827, 80.2707, "a major automobile and IT hub on the Bay of Bengal"),
    ("Kolkata", "West Bengal", 22.5726, 88.3639, "India's cultural capital, known for its colonial architecture"),
    ("Surat", "Gujarat", 21.1702, 72.8311, "the diamond and textile capital of India"),
    ("Pune", "Maharashtra", 18.5204, 73.8567, "a major education and IT hub in western Maharashtra"),
    ("Jaipur", "Rajasthan", 26.9124, 75.7873, "the Pink City, known for its forts and palaces"),
    ("Lucknow", "Uttar Pradesh", 26.8467, 80.9462, "the capital of Uttar Pradesh, known for its Nawabi culture"),
    ("Kanpur", "Uttar Pradesh", 26.4499, 80.3319, "a major industrial city on the banks of the Ganges"),
    ("Nagpur", "Maharashtra", 21.1458, 79.0882, "the orange city and geographic centre of India"),
    ("Indore", "Madhya Pradesh", 22.7196, 75.8577, "Madhya Pradesh's commercial hub, known for its street food"),
    ("Thane", "Maharashtra", 19.2183, 72.9781, "a fast-growing city in the Mumbai Metropolitan Region"),
    ("Bhopal", "Madhya Pradesh", 23.2599, 77.4126, "the capital of Madhya Pradesh, known as the city of lakes"),
    ("Visakhapatnam", "Andhra Pradesh", 17.6868, 83.2185, "a major port city on the east coast, also called Vizag"),
    ("Patna", "Bihar", 25.5941, 85.1376, "the capital of Bihar, one of the world's oldest continuously inhabited cities"),
    ("Vadodara", "Gujarat", 22.3072, 73.1812, "a cultural and industrial city in central Gujarat"),
    ("Ghaziabad", "Uttar Pradesh", 28.6692, 77.4538, "a major industrial city in the Delhi NCR region"),
    ("Ludhiana", "Punjab", 30.9010, 75.8573, "Punjab's largest city and a major industrial hub"),
    ("Agra", "Uttar Pradesh", 27.1767, 78.0081, "home to the Taj Mahal, one of the world's most iconic monuments"),
    ("Nashik", "Maharashtra", 19.9975, 73.7898, "a wine-producing city and one of Hinduism's Kumbh Mela sites"),
    ("Faridabad", "Haryana", 28.4089, 77.3178, "a major industrial city in the Delhi NCR region"),
    ("Meerut", "Uttar Pradesh", 28.9845, 77.7064, "a historic city known as the starting point of the 1857 uprising"),
    ("Rajkot", "Gujarat", 22.3039, 70.8022, "a major industrial and commercial city in Saurashtra"),
    ("Varanasi", "Uttar Pradesh", 25.3176, 82.9739, "one of the oldest continuously inhabited cities, sacred to Hindus"),
    ("Srinagar", "Jammu and Kashmir", 34.0837, 74.7973, "the summer capital of Jammu & Kashmir, known for Dal Lake"),
    ("Aurangabad", "Maharashtra", 19.8762, 75.3433, "a historic city near the Ajanta and Ellora caves"),
    ("Amritsar", "Punjab", 31.6340, 74.8723, "home to the Golden Temple, Sikhism's holiest shrine"),
    ("Navi Mumbai", "Maharashtra", 19.0330, 73.0297, "a planned satellite city across the harbour from Mumbai"),
    ("Prayagraj", "Uttar Pradesh", 25.4358, 81.8463, "the confluence city (Allahabad), site of the Kumbh Mela"),
    ("Ranchi", "Jharkhand", 23.3441, 85.3096, "the capital of Jharkhand, known as the city of waterfalls"),
    ("Howrah", "West Bengal", 22.5958, 88.2636, "a major railway and industrial city across the Hooghly from Kolkata"),
    ("Coimbatore", "Tamil Nadu", 11.0168, 76.9558, "a major textile and manufacturing hub in western Tamil Nadu"),
    ("Jabalpur", "Madhya Pradesh", 23.1815, 79.9864, "a historic city on the Narmada river"),
    ("Gwalior", "Madhya Pradesh", 26.2183, 78.1828, "a historic city known for its hilltop fort"),
    ("Vijayawada", "Andhra Pradesh", 16.5062, 80.6480, "a major commercial city on the banks of the Krishna river"),
    ("Jodhpur", "Rajasthan", 26.2389, 73.0243, "the Blue City, known for Mehrangarh Fort"),
    ("Madurai", "Tamil Nadu", 9.9252, 78.1198, "a temple city famed for the Meenakshi Amman Temple"),
    ("Raipur", "Chhattisgarh", 21.2514, 81.6296, "the capital of Chhattisgarh and a growing steel hub"),
    ("Kota", "Rajasthan", 25.2138, 75.8648, "known nationally as India's coaching and education hub"),
    # Guwahati intentionally omitted — no dedicated Guwahati page on this site.
    ("Chandigarh", "Chandigarh", 30.7333, 76.7794, "a planned city that is the joint capital of Punjab and Haryana"),
    ("Thiruvananthapuram", "Kerala", 8.5241, 76.9366, "the capital of Kerala, known for its palaces and beaches"),
    ("Solapur", "Maharashtra", 17.6599, 75.9064, "a textile city in southern Maharashtra"),
    ("Hubballi-Dharwad", "Karnataka", 15.3647, 75.1240, "a twin-city commercial hub in northern Karnataka"),
    ("Tiruchirappalli", "Tamil Nadu", 10.7905, 78.7047, "a historic city known as Trichy, home to the Rockfort Temple"),
    ("Bareilly", "Uttar Pradesh", 28.3670, 79.4304, "known for its furniture and zari craft industry"),
    ("Mysuru", "Karnataka", 12.2958, 76.6394, "the royal city of Karnataka, known for Mysore Palace"),
    ("Tiruppur", "Tamil Nadu", 11.1085, 77.3411, "India's knitwear and garment export hub"),
    ("Gurugram", "Haryana", 28.4595, 77.0266, "a major corporate and IT hub in the Delhi NCR region"),
    ("Aligarh", "Uttar Pradesh", 27.8974, 78.0880, "known for its lock industry and Aligarh Muslim University"),
    ("Jalandhar", "Punjab", 31.3260, 75.5762, "a major sports goods manufacturing city in Punjab"),
    ("Bhubaneswar", "Odisha", 20.2961, 85.8245, "the temple city and capital of Odisha"),
    ("Salem", "Tamil Nadu", 11.6643, 78.1460, "known as the steel city of Tamil Nadu"),
    ("Warangal", "Telangana", 17.9689, 79.5941, "a historic city known for the Kakatiya-era Thousand Pillar Temple"),
    ("Guntur", "Andhra Pradesh", 16.3067, 80.4365, "a major agricultural trade centre in Andhra Pradesh"),
    ("Bhiwandi", "Maharashtra", 19.3002, 73.0629, "a major textile and logistics hub near Mumbai"),
    ("Saharanpur", "Uttar Pradesh", 29.9640, 77.5460, "known nationally for its wood carving industry"),
    ("Gorakhpur", "Uttar Pradesh", 26.7606, 83.3732, "home to the Gorakhnath Temple in eastern Uttar Pradesh"),
    ("Bikaner", "Rajasthan", 28.0229, 73.3119, "a desert city in Rajasthan known for its forts and sweets"),
    ("Amravati", "Maharashtra", 20.9374, 77.7796, "an agricultural trade centre in the Vidarbha region"),
    ("Noida", "Uttar Pradesh", 28.5355, 77.3910, "a major planned business and IT hub in Delhi NCR"),
    ("Jamshedpur", "Jharkhand", 22.8046, 86.2029, "India's first planned industrial city, home to Tata Steel"),
    ("Bhilai", "Chhattisgarh", 21.1938, 81.3509, "a steel city and industrial centre in Chhattisgarh"),
    ("Cuttack", "Odisha", 20.4625, 85.8828, "the former capital and commercial hub of Odisha"),
    ("Kochi", "Kerala", 9.9312, 76.2673, "a major port city known as the Queen of the Arabian Sea"),
    ("Nellore", "Andhra Pradesh", 14.4426, 79.9865, "an agricultural and aquaculture centre in coastal Andhra Pradesh"),
    ("Bhavnagar", "Gujarat", 21.7645, 72.1519, "a coastal industrial city in Saurashtra, Gujarat"),
    ("Dehradun", "Uttarakhand", 30.3165, 78.0322, "the capital of Uttarakhand, nestled in the Himalayan foothills"),
    ("Durgapur", "West Bengal", 23.5204, 87.3119, "a major steel and industrial city in West Bengal"),
    ("Asansol", "West Bengal", 23.6739, 86.9524, "a coal and industrial hub in West Bengal"),
    ("Jammu", "Jammu and Kashmir", 32.7266, 74.8570, "the winter capital of Jammu & Kashmir"),
    ("Mangaluru", "Karnataka", 12.9141, 74.8560, "a major port city on Karnataka's west coast"),
    ("Erode", "Tamil Nadu", 11.3410, 77.7172, "known as the turmeric city of Tamil Nadu"),
    ("Belagavi", "Karnataka", 15.8497, 74.4977, "a historic city on the Maharashtra-Karnataka border"),
    ("Kurnool", "Andhra Pradesh", 15.8281, 78.0373, "a historic city on the banks of the Tungabhadra"),
    ("Rajahmundry", "Andhra Pradesh", 17.0005, 81.8040, "a culturally significant city on the banks of the Godavari"),
    ("Tirunelveli", "Tamil Nadu", 8.7139, 77.7567, "a historic temple town in southern Tamil Nadu"),
    ("Gaya", "Bihar", 24.7955, 84.9994, "a major Buddhist and Hindu pilgrimage centre near Bodh Gaya"),
    ("Udaipur", "Rajasthan", 24.5854, 73.7125, "the City of Lakes, known for its palaces"),
    ("Kozhikode", "Kerala", 11.2588, 75.7804, "a historic port city on Kerala's Malabar coast"),
    ("Tirupati", "Andhra Pradesh", 13.6288, 79.4192, "home to the Sri Venkateswara Temple, one of the world's most visited shrines"),
    ("Panipat", "Haryana", 29.3909, 76.9635, "a historic city known for its textile industry"),
    ("Shimla", "Himachal Pradesh", 31.1048, 77.1734, "the capital of Himachal Pradesh, a Himalayan hill station"),
    ("Puducherry", "Puducherry", 11.9416, 79.8083, "a former French colony known for its coastal promenade"),
    ("Itanagar", "Arunachal Pradesh", 27.0844, 93.6053, "the capital of Arunachal Pradesh in the eastern Himalayas"),
    ("Kohima", "Nagaland", 25.6751, 94.1086, "the capital of Nagaland, known for the Hornbill Festival"),
    ("Imphal", "Manipur", 24.8170, 93.9368, "the capital of Manipur, known for Loktak Lake nearby"),
    ("Aizawl", "Mizoram", 23.1645, 92.9376, "the hilltop capital of Mizoram"),
    ("Gangtok", "Sikkim", 27.3389, 88.6065, "the Himalayan capital of Sikkim, near Kangchenjunga"),
    ("Agartala", "Tripura", 23.8315, 91.2868, "the capital of Tripura, home to Ujjayanta Palace"),
    ("Shillong", "Meghalaya", 25.5788, 91.8933, "the capital of Meghalaya, known as the Scotland of the East"),
    ("Panaji", "Goa", 15.4909, 73.8278, "the capital of Goa, on the banks of the Mandovi river"),
    ("Leh", "Ladakh", 34.1526, 77.5771, "the high-altitude capital of Ladakh in the Himalayas"),
    ("Port Blair", "Andaman and Nicobar Islands", 11.6234, 92.7265, "the capital of the Andaman & Nicobar Islands"),
    ("Ajmer", "Rajasthan", 26.4499, 74.6399, "home to the Ajmer Sharif Dargah, a major pilgrimage site"),
    ("Ujjain", "Madhya Pradesh", 23.1765, 75.7885, "one of Hinduism's seven sacred cities, host to the Kumbh Mela"),
    ("Siliguri", "West Bengal", 26.7271, 88.3953, "a major gateway city to Northeast India and the eastern Himalayas"),
    ("Jhansi", "Uttar Pradesh", 25.4484, 78.5685, "a historic city known for the Rani of Jhansi's fort"),
    ("Rourkela", "Odisha", 22.2604, 84.8536, "a major steel city in Odisha"),
    ("Kolhapur", "Maharashtra", 16.7050, 74.2433, "a historic city in southern Maharashtra known for its temple heritage"),
    ("Dhanbad", "Jharkhand", 23.7957, 86.4304, "the coal capital of India"),
]
